name = "web-tracking-dashboard"
compatibility_date = "2025-08-21"

pages_build_output_dir = "out"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.preview]
vars = { ENVIRONMENT = "preview" }
